---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: "Move backend files to server."
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extruct archive
  shell: |
    cd /home/ubuntu/backend
    ansible.builtin.unarchive:
    tar -xzvf artifact.tar.gz .
    # rm artifact.tar.gz

- name: Install Node
  shell: |
    cd /home/ubuntu/backend
    npm install -g 13.8.0

- name: "install npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    npm run prestart:prod
  args:
    chdir: /home/ubuntu/backend

- name: Download zsh installer
  get_url:
    url: https://deb.nodesource.com/setup_13.x
    dest: /tmp/setup_13.sh

- name: Execute the setup_13.sh
  become: true
  become_user: root
  shell: chmod 777 setup_13.sh & bash setup_13.sh
  args:
    chdir: /tmp/

- name: "install pm2"
  become: true
  npm:
    name: pm2
    path: /home/ubuntu/backend
    global: yes
    production: yes
    state: present

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    # npm run build
    pm2 stop default
    #cd dist
    pm2 start npm  --name backend -- run start